### ISSUE TITLE
Pyperclip on limited env (no GUI)

### ISSUE THREAD

**Issue by herpiko** [BlankOn/tempel-cli-py#9]
@nsiregar

This doesnt play well in limited env like no GUI. Since there is no copy/paste, it thrown error : 

```
deploy@ubuntu-1gb-sgp1-01:~/src/tempel-cli-py$ ./tempel 
Traceback (most recent call last):
  File "./tempel", line 76, in <module>
    get_args()
  File "./tempel", line 43, in get_args
    content = pyperclip.paste() #default source of tempel is string from clipboard
  File "/usr/local/lib/python2.7/dist-packages/pyperclip/clipboards.py", line 125, in __call__
    raise PyperclipException(EXCEPT_MSG)
pyperclip.exceptions.PyperclipException: 
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit https://pyperclip.readthedocs.org 
deploy@ubuntu-1gb-sgp1-01:~/src/tempel-cli-py$ 
```

Can you catch it?

**Comment by nsiregar** [comment]
Updated on new commit, while running on limited env `tempel` will display help
![screenshot from 2016-11-07 08-56-32](https://cloud.githubusercontent.com/assets/18432852/20043069/d6f6da06-a4c9-11e6-89f0-20d8d1c3cea0.png)

**Comment by herpiko** [comment]
#8
